language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

install:
  # Force install an old version of isort (see https://github.com/timothycrosley/isort/issues/1273)
  - "pip install flake8 pylint pytest requests 'isort<5.0'"

script:
  - "make flake8"
  - "make pylint"
  - "make pytest"
  - "make validate-style"
